[package]
name = "lesson-02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-vowel = "0.1.0"
slug = "0.1.5"
