workspace = { members = ["lesson-7"] }
[package]
name = "lesson-5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
is-vowel = "0.1.0"
lazy_static = "1.4.0"
slug = "0.1.5"
